### ISSUE TITLE
Problem with NA's

### ISSUE THREAD

**Issue by Nowosad** [edzer/sfr#99]
`sf` behaviour is different when `NA` is in column with integers and when `NA` is in column with numeric. I've added two new columns with NA, the first one is an integer and the second one is a numeric:

```
> nc <- st_read(system.file("shape/nc.shp", package="sf"))
> nc$integer <- as.integer(NA)
> nc$numeric <- as.numeric(NA)
> head(nc)
Simple feature collection with 6 features and 16 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -81.74107 ymin: 36.07282 xmax: -75.77316 ymax: 36.58965
epsg (SRID):    4267
proj4string:    +proj=longlat +datum=NAD27 +no_defs
   AREA PERIMETER CNTY_ CNTY_ID        NAME  FIPS FIPSNO CRESS_ID BIR74 SID74 NWBIR74 BIR79 SID79 NWBIR79                       geometry integer numeric
1 0.114     1.442  1825    1825        Ashe 37009  37009        5  1091     1      10  1364     0      19 MULTIPOLYGON(((-81.47275543...      NA      NA
2 0.061     1.231  1827    1827   Alleghany 37005  37005        3   487     0      10   542     3      12 MULTIPOLYGON(((-81.23989105...      NA      NA
3 0.143     1.630  1828    1828       Surry 37171  37171       86  3188     5     208  3616     6     260 MULTIPOLYGON(((-80.45634460...      NA      NA
4 0.070     2.968  1831    1831   Currituck 37053  37053       27   508     1     123   830     2     145 MULTIPOLYGON(((-76.00897216...      NA      NA
5 0.153     2.206  1832    1832 Northampton 37131  37131       66  1421     9    1066  1606     3    1197 MULTIPOLYGON(((-77.21766662...      NA      NA
6 0.097     1.670  1833    1833    Hertford 37091  37091       46  1452     7     954  1838     5    1237 MULTIPOLYGON(((-76.74506378...      NA      NA
```
I've saved them to `.gpkg` file:

```
> st_write(nc, 'temp.gpkg')
> nc_new <- st_read('temp.gpkg')
> head(nc_new)
Simple feature collection with 6 features and 16 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -81.74107 ymin: 36.07282 xmax: -75.77316 ymax: 36.58965
epsg (SRID):    4267
proj4string:    +proj=longlat +datum=NAD27 +no_defs
   AREA PERIMETER CNTY_ CNTY_ID        NAME  FIPS FIPSNO CRESS_ID BIR74 SID74 NWBIR74 BIR79 SID79 NWBIR79 integer numeric                           geom
1 0.114     1.442  1825    1825        Ashe 37009  37009        5  1091     1      10  1364     0      19      NA       0 MULTIPOLYGON(((-81.47275543...
2 0.061     1.231  1827    1827   Alleghany 37005  37005        3   487     0      10   542     3      12      NA       0 MULTIPOLYGON(((-81.23989105...
3 0.143     1.630  1828    1828       Surry 37171  37171       86  3188     5     208  3616     6     260      NA       0 MULTIPOLYGON(((-80.45634460...
4 0.070     2.968  1831    1831   Currituck 37053  37053       27   508     1     123   830     2     145      NA       0 MULTIPOLYGON(((-76.00897216...
5 0.153     2.206  1832    1832 Northampton 37131  37131       66  1421     9    1066  1606     3    1197      NA       0 MULTIPOLYGON(((-77.21766662...
6 0.097     1.670  1833    1833    Hertford 37091  37091       46  1452     7     954  1838     5    1237      NA       0 MULTIPOLYGON(((-76.74506378...
```

Now, the first one (integer) still has NA values, while the second one (numeric) has 0. 

I also read a file into QGIS, where the numeric column has no value, while the integer column have values of "-2147483648"
![screenshot from 2016-12-05 15-54-18](https://cloud.githubusercontent.com/assets/3457131/20902206/1b5ccdf4-bb04-11e6-8d14-6387dae20b8b.png)

**Comment by edzer** [comment]
The [geopackage standard](http://www.geopackage.org/spec/#attributes) doesn't say much about this; I'm also not sure whether this should be addressed here or in the [GPKG driver](http://www.gdal.org/drv_geopackage.html). Since GPKG is sqlite, maybe you could check whether RSQLite round-trips NA values correctly?

**Comment by Nowosad** [comment]
@edzer I've checked SHAPEFILE:

```
> st_write(nc, 'temp.shp')
> nc_new <- st_read('temp.shp')
> head(nc_new)
Simple feature collection with 6 features and 16 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -81.74107 ymin: 36.07282 xmax: -75.77316 ymax: 36.58965
epsg (SRID):    4267
proj4string:    +proj=longlat +datum=NAD27 +no_defs
   AREA PERIMETER CNTY_ CNTY_ID        NAME  FIPS FIPSNO CRESS_ID BIR74 SID74 NWBIR74 BIR79 SID79 NWBIR79     integer
1 0.114     1.442  1825    1825        Ashe 37009  37009        5  1091     1      10  1364     0      19 -2147483648
2 0.061     1.231  1827    1827   Alleghany 37005  37005        3   487     0      10   542     3      12 -2147483648
3 0.143     1.630  1828    1828       Surry 37171  37171       86  3188     5     208  3616     6     260 -2147483648
4 0.070     2.968  1831    1831   Currituck 37053  37053       27   508     1     123   830     2     145 -2147483648
5 0.153     2.206  1832    1832 Northampton 37131  37131       66  1421     9    1066  1606     3    1197 -2147483648
6 0.097     1.670  1833    1833    Hertford 37091  37091       46  1452     7     954  1838     5    1237 -2147483648
  numeric                       geometry
1     NaN MULTIPOLYGON(((-81.47275543...
2     NaN MULTIPOLYGON(((-81.23989105...
3     NaN MULTIPOLYGON(((-80.45634460...
4     NaN MULTIPOLYGON(((-76.00897216...
5     NaN MULTIPOLYGON(((-77.21766662...
6     NaN MULTIPOLYGON(((-76.74506378... 
```

It doesn't look like a geopackage problem, but rather it's something bigger. I have Fedora 24 with  GEOS 3.5.0 and GDAL 2.1.2. Maybe somebody could try to replicate this using a different system?

**Comment by edzer** [comment]
Does GDAL have a concept of missing-valued feature attributes?

**Comment by edzer** [comment]
Should be fixed now, both ways, please report back when you've tried out!

**Comment by Nowosad** [comment]
Works well with GPKG, but there is still a problem with SHP:


```
> nc <- st_read(system.file("shape/nc.shp", package="sf"))
> nc$integer <- as.integer(NA)
> nc$numeric <- as.numeric(NA)
> 
> st_write(nc, 'temp.gpkg')
> nc_new <- st_read('temp.gpkg')
> head(nc_new)
Simple feature collection with 6 features and 16 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -81.74107 ymin: 36.07282 xmax: -75.77316 ymax: 36.58965
epsg (SRID):    4267
proj4string:    +proj=longlat +datum=NAD27 +no_defs
   AREA PERIMETER CNTY_ CNTY_ID        NAME  FIPS FIPSNO CRESS_ID BIR74 SID74
1 0.114     1.442  1825    1825        Ashe 37009  37009        5  1091     1
2 0.061     1.231  1827    1827   Alleghany 37005  37005        3   487     0
3 0.143     1.630  1828    1828       Surry 37171  37171       86  3188     5
4 0.070     2.968  1831    1831   Currituck 37053  37053       27   508     1
5 0.153     2.206  1832    1832 Northampton 37131  37131       66  1421     9
6 0.097     1.670  1833    1833    Hertford 37091  37091       46  1452     7
  NWBIR74 BIR79 SID79 NWBIR79 integer numeric                           geom
1      10  1364     0      19      NA      NA MULTIPOLYGON(((-81.47275543...
2      10   542     3      12      NA      NA MULTIPOLYGON(((-81.23989105...
3     208  3616     6     260      NA      NA MULTIPOLYGON(((-80.45634460...
4     123   830     2     145      NA      NA MULTIPOLYGON(((-76.00897216...
5    1066  1606     3    1197      NA      NA MULTIPOLYGON(((-77.21766662...
6     954  1838     5    1237      NA      NA MULTIPOLYGON(((-76.74506378...
> 
> st_write(nc, 'temp.shp')
> nc_new <- st_read('temp.shp')
> head(nc_new)
Simple feature collection with 6 features and 16 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -81.74107 ymin: 36.07282 xmax: -75.77316 ymax: 36.58965
epsg (SRID):    4267
proj4string:    +proj=longlat +datum=NAD27 +no_defs
   AREA PERIMETER CNTY_ CNTY_ID        NAME  FIPS FIPSNO CRESS_ID BIR74 SID74
1 0.114     1.442  1825    1825        Ashe 37009  37009        5  1091     1
2 0.061     1.231  1827    1827   Alleghany 37005  37005        3   487     0
3 0.143     1.630  1828    1828       Surry 37171  37171       86  3188     5
4 0.070     2.968  1831    1831   Currituck 37053  37053       27   508     1
5 0.153     2.206  1832    1832 Northampton 37131  37131       66  1421     9
6 0.097     1.670  1833    1833    Hertford 37091  37091       46  1452     7
  NWBIR74 BIR79 SID79 NWBIR79 integer numeric                       geometry
1      10  1364     0      19      NA     NaN MULTIPOLYGON(((-81.47275543...
2      10   542     3      12      NA     NaN MULTIPOLYGON(((-81.23989105...
3     208  3616     6     260      NA     NaN MULTIPOLYGON(((-80.45634460...
4     123   830     2     145      NA     NaN MULTIPOLYGON(((-76.00897216...
5    1066  1606     3    1197      NA     NaN MULTIPOLYGON(((-77.21766662...
6     954  1838     5    1237      NA     NaN MULTIPOLYGON(((-76.74506378...
```

**Comment by edzer** [comment]
This is the same with `rgdal::readOGR`, so it may be a problem of the shapefile driver in `GDAL` (both sf and rgdal check IsFieldSet() and set the return value to NA_REAL if negative).
